# Show help, place this first so it runs with just `make`
help:
	@printf "\nCommands:\n"
	@printf "\033[32mservices\033[0m        run services using Docker\n"
	@printf "\033[32mservices-stop\033[0m   stop the running Docker services\n"
	@printf "\033[32mcheck\033[0m           run ruff linter and formatter checks\n"
	@printf "\033[32mtest\033[0m            run unit tests with pytest\n"
	@printf "\033[32mclean\033[0m           remove ruff and pytest cache directories\n"

# Run services using Docker
services:
	docker compose --file deployment/compose.yml up --detach

# Stop the running Docker services and remove volumes attached to containers
services-stop:
	docker compose --file deployment/compose.yml down --volumes

# Run linter and formatter checks using ruff
check:
	ruff check src
	ruff format --check src

# Run unit tests using pytest
test:
	pytest --ignore=tests/decorator_tests/ml_tests/llm_tests

# Remove cache directories generated by ruff and pytest
clean:
	rm -rf .ruff_cache
	rm -rf .pytest_cache
