plugins:
  # For each key below, you can have multiple instances. Like mlflow1, mlflow2; zambeze1, zambeze2.
  zambeze:
    kind: zambeze
    host: localhost
    port: 5672
    queue_name: hello
    key_values_to_filter:
      - key: activity_status
        value: CREATED
    keys_to_intercept:
      - arguments
      - kwargs
      - files
      - name
      - activity_id
    enrich_messages: true

  mlflow:
    kind: mlflow
    file_path: mlflow.db
    log_params: ['*']
    log_metrics: ['*']
    redis_host: localhost
    redis_port: 60379
    watch_interval_sec: 2
    enrich_messages: true

  tensorboard:
    kind: tensorboard
    file_path: tensorboard_events
    log_tags: ['scalars', 'hparams', 'tensors']
    log_metrics: ['accuracy']
    redis_host: localhost
    redis_port: 60379
    watch_interval_sec: 5
    enrich_messages: true

  dask:
    kind: dask
    redis_host: localhost
    redis_port: 60379
    enrich_messages: true
    worker_should_get_input: true
    scheduler_should_get_input: true
    worker_should_get_output: true
    scheduler_create_timestamps: true
    worker_create_timestamps: false
