plugins:
  zambeze:
    type: message_broker
    subtype: rabbit_mq
    host: localhost
    port: 5672
    queue_name: hello
    key_values_to_filter:
      - key: activity_status
        value: CREATED
    keys_to_intercept:
      - arguments
      - kwargs
      - files
      - name
      - activity_id
