plugins:
  # For each key below, you can have multiple instances. Like mlflow1, mlflow2; zambeze1, zambeze2.
  zambeze:
    kind: zambeze
    observer_type: message_broker
    observer_subtype: rabbit_mq
    host: localhost
    port: 5672
    queue_name: hello
    key_values_to_filter:
      - key: activity_status
        value: CREATED
    keys_to_intercept:
      - arguments
      - kwargs
      - files
      - name
      - activity_id

  mlflow:
    kind: mlflow
    observer_type: file
    observer_subtype: sqlite
    file_path: mlflow.db
    log_params: ['*']
    log_metrics: ['*']
    redis_host: localhost
    redis_port: 60379
    watch_interval_sec: 2

  tensorboard:
    kind: tensorboard
    observer_type: file
    observer_subtype: binary
    file_path: tensorboard_events
    log_tags: ['scalars', 'hparams', 'tensors']
    log_metrics: ['accuracy']
    redis_host: localhost
    redis_port: 60379

    watch_interval_sec: 5

  dask:
    kind: dask
    observer_type: outsourced
    redis_host: localhost
    redis_port: 60379
    enrich_messages: true


