version: '3.8'
services:
  flowcept_redis:
    container_name: flowcept_redis
    image: redis
    ports:
      - 6379:6379

  mlflow_interceptor_redis:
    container_name: mlflow_interceptor_redis
    image: redis
    ports:
      - 60379:6379

  zambeze_rabbitmq:
    container_name: zambeze_rabbitmq
    image: rabbitmq:3.11-management
    ports:
      - 5672:5672
      - 15672:15672
