version: '3.8'
name: flowcept
services:
  flowcept_redis:
    container_name: flowcept_redis
    image: redis
    ports:
      - 6379:6379

  flowcept_mongo:
    container_name: flowcept_mongo
    image: mongo:latest
    ports:
      - 27017:27017

  local_interceptor_cache:
    container_name: local_interceptor_cache
    image: redis
    ports:
      - 60379:6379

  zambeze_rabbitmq:
    container_name: zambeze_rabbitmq
    image: rabbitmq:3.11-management
    ports:
      - 5672:5672
      - 15672:15672
