# Use the command `make build` to build this image.
# Use conda-forge base image consistently across local/CI.
FROM condaforge/miniforge3:23.11.0-0

WORKDIR /flowcept

COPY pyproject.toml Makefile README.md ./
COPY src ./src
COPY resources ./resources
COPY notebooks ./notebooks
COPY tests ./tests
COPY examples ./examples

# Create env + install flowcept
RUN conda create -n flowcept python=3.11.10 -y && \
    conda run -n flowcept pip install -e .[lmdb,telemetry,dev,llm_agent,extras]

# Set env variables properly
ENV FLOWCEPT_SETTINGS_PATH=/flowcept/resources/sample_settings.yaml

# Expose MCP port
EXPOSE 8003

# Start agent directly
CMD ["conda", "run", "--no-capture-output", "-n", "flowcept", "flowcept", "--start-agent"]
