name: Version Bumper
on: push
jobs:
  build:
    name: Version Bumper
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Get branch names
        id: branch-name
        uses: tj-actions/branch-names@v6
      - name: Update version.py
        run: |
          export PYTHONPATH=$PYTHONPATH:flowcept
          export BRANCH_NAME="${{ steps.branch-name.outputs.base_ref_branch }}"
          echo Base Branch ${{ steps.branch-name.outputs.base_ref_branch }}
          echo Current Branch ${{ steps.branch-name.outputs.current_branch }}
          echo Base ref Branch ${{ steps.branch-name.outputs.ref_branch }}
          echo Head ref Branch ${{ steps.branch-name.outputs.head_ref_branch }}
          
          python .github/workflows/version_bumper.py
      - name: Commit new version
        run: |
          git config --global user.name 'Flowcept CI Bot'
          git config --global user.email 'flowcept@users.noreply.github.com'
          git add flowcept/version.py
          git commit -m "Automated version bumping"
          git push --force 
