name: Push commit
on: push
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create report file
        run: date +%s > report.txt
      - name: Commit report
        run: |
          git config --global user.name 'Renan Souza'
          git config --global user.email 'renan-souza@users.noreply.github.com'
          git commit -am "Automated report"
          git push
