name: Push commit
on: push
jobs:
  bump_version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create report file
        run: date +%s > report.txt
      - name: Commit report
        run: |
          git status
          ls -l
          git config --global user.name 'Renan Souza'
          git config --global user.email 'renan-souza@users.noreply.github.com'
          git add report.txt
          git commit -m "Automated version bumping"
          git push
