- name: GIT commit and push docs
  env: 
    CI_COMMIT_MESSAGE: [CI] Bumping version
    CI_COMMIT_AUTHOR: Continuous Integration
  run: |
    ls
    git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
    git config --global user.email "username@users.noreply.github.com"
    touch test
    git add test
    git commit -m "${{ env.CI_COMMIT_MESSAGE }}"
    git push
