name: Version Bumper
on: [push, pull_request]
jobs:
  build:
    name: Version Bumper
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
#      - name: Install dependencies
#        run: |
#          python -m pip install --upgrade pip
#          pip install GitPython
      - name: Get branch names
        id: branch-name
        uses: tj-actions/branch-names@v6
      - name: Update version.py
        run: |
          export PYTHONPATH=$PYTHONPATH:flowcept
          export BRANCH_NAME="${{ steps.branch-name.outputs.ref_branch }}"
          python .github/workflows/version_bumper.py
      - name: Commit new version
        run: |
          git config --global user.name 'Flowcept CI Bot'
          git config --global user.email 'flowcept@users.noreply.github.com'
          git add flowcept/version.py
          git commit -m "Automated version bumping"
          git push --force 
