name: Linter, formatter, and docs checks

on: pull_request

jobs:

  checks:
    runs-on: ubuntu-22.04
    if: "!contains(github.event.head_commit.message, 'CI Bot')"

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install package and dependencies
        run: |
          pip install --upgrade pip
          pip install ruff
          pip install .[docs]

      - name: Run linter and formatter checks using ruff
        # run: make checks
        run: ruff format --check --diff src

      - name: Run HTML builder for Sphinx documentation
        run: make docs
