name: Create Release
on: push
jobs:
  build:
    env:
      CURRENT_VERSION: place-holder
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Get current version
        run: |
          export PYTHONPATH=$PYTHONPATH:flowcept
          export CURRENT_VERSION=`python -c "from flowcept import __version__; print(__version__)"`
          echo $CURRENT_VERSION
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
          CURRENT_VERSION: ${CURRENT_VERSION}
        with:
          tag_name: ${CURRENT_VERSION}
          release_name: Release ${CURRENT_VERSION}
          body: "Automated message"
          draft: false
          prerelease: true

