name: Create Release
on: push
jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Get current version
        run: |
          export PYTHONPATH=$PYTHONPATH:flowcept
          export CURRENT_VERSION=`python -c "from flowcept import __version__; print(__version__)"`
          echo $CURRENT_VERSION
      - name: "Create release"
        uses: "actions/github-script@v5"
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          script: |
            try {
              await github.rest.repos.createRelease({
                draft: false,
                generate_release_notes: true,
                name: process.env.CURRENT_VERSION,
                owner: context.repo.owner,
                prerelease: false,
                repo: context.repo.repo,
                tag_name: process.env.CURRENT_VERSION,
              });
            } catch (error) {
              core.setFailed(error.message);
            }
