name: All tests on Kafka MQ
on: [push]
# branches: [ "disabled" ]

jobs:

  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    if: "!contains(github.event.head_commit.message, 'CI Bot')"
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Check python version
      run: python --version
    - name: Install our dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[fulldev]
    - name: Run Docker Compose
      run: docker compose -f deployment/compose-kafka.yml up -d
    - name: Wait 1 min
      run: sleep 60
    - name: Check liveness
      run: |
        export MQ_TYPE=kafka
        export MQ_PORT=9092
        python -c 'from flowcept.configs import MQ_TYPE, MQ_PORT; print(f"MQ_TYPE={MQ_TYPE}"); print(f"MQ_TYPE={MQ_PORT}")'
        python -c 'from flowcept import FlowceptConsumerAPI; assert FlowceptConsumerAPI.services_alive()'
    - name: Run Tests with Kafka
      run: |
        export MQ_TYPE=kafka
        export MQ_PORT=9092
        pytest --ignore=tests/decorator_tests/ml_tests/llm_tests
    - name: Test notebooks
      run: |
        pip install -e .[full]
        export MQ_TYPE=kafka
        export MQ_PORT=9092
        python -c 'from flowcept.configs import MQ_TYPE, MQ_PORT; print(f"MQ_TYPE={MQ_TYPE}"); print(f"MQ_TYPE={MQ_PORT}")'
        python -c 'from flowcept import FlowceptConsumerAPI; assert FlowceptConsumerAPI.services_alive()'
        
        python flowcept/flowcept_webserver/app.py &
        sleep 3
        export FLOWCEPT_SETTINGS_PATH=~/.flowcept/settings.yaml
        pytest --nbmake "notebooks/" --nbmake-timeout=600 --ignore=notebooks/dask_from_CLI.ipynb
