name: Unit Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Run Redis
      run: docker run -p 6379:6379 --name redis -d redis
    - name: Run RabbitMQ for Zambeze tests
      run: docker run -it --rm --name rabbitmq -p 5672:5672 -p 15672:15672 -d rabbitmq:3.11-management
    - name: Check python version
      run: python --version
    - name: Install our dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Install plugin dependencies
      run: |               
        if [ -f requirements_plugins ]; then for requirement_file in `ls requirements_plugins`; do pip install -r $requirement_file; done; fi
    - name: Test with pytest
      run: |
        pytest