name: Unit Tests
on: [push, pull_request]

jobs:

  build:

    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'CI Bot')"
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Check python version
      run: python --version
    - name: Install our dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Install plugin dependencies
      run: |               
        if [ -d extra_requirements ]; then
          for requirements_file in `ls extra_requirements`; do
            echo requirements_file;
            pip install -r extra_requirements/$requirements_file; 
          done;
        fi
    - name: Run Docker Compose
      run: docker compose -f deployment/compose.yml up
    - name: Test with pytest
      run: |
        pytest
