name: Test Python 3.9
on:
  pull_request:
    #branches: [ "dev", "main" ]
    branches: [ "disabled" ]

jobs:

  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'CI Bot')"
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Check python version
      run: python --version
    - name: Install our dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[full]
        pip install -r extra_requirements/dev-requirements.txt
    - name: Run Docker Compose
      run: docker compose -f deployment/compose.yml up -d
    - name: Test with pytest
      run: |
        pytest # --ignore=tests/plugins/test_tensorboard.py
    - name: Test notebooks
      run: |
        python flowcept/flowcept_webserver/app.py &
        sleep 3
        pytest --nbmake "notebooks/" --ignore=notebooks/dask_from_CLI.ipynb
