name: Test Python 3.10 - MacOS
on:
  pull_request:
    branches: [ "dev", "main" ]
jobs:
  build:
    runs-on: macos-latest
    if: "!contains(github.event.head_commit.message, 'CI Bot')"
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Check python version
      run: python --version
    - name: Install our dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[full]
        pip install -r extra_requirements/dev-requirements.txt
    - name: Install docker
      run: |
        brew install docker docker-compose 
        colima start
        mkdir -p ~/.docker/cli-plugins
        ln -sfn /usr/local/opt/docker-compose/bin/docker-compose ~/.docker/cli-plugins/docker-compose
    - name: Run Docker Compose
      run: |
        docker compose version
        docker compose -f deployment/compose.yml up -d
    - name: Test with pytest
      run: |
        pytest # --ignore=tests/plugins/test_tensorboard.py
    - name: Test notebooks
      run: |
        python flowcept/flowcept_webserver/app.py &
        sleep 3
        pytest --nbmake "notebooks/" --nbmake-timeout=600 --ignore=notebooks/dask_from_CLI.ipynb
